# Generated by Django 5.2.8 on 2025-11-21 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Fim')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Concluído'), ('CANCELED_BY_PATIENT', 'Cancelado pelo paciente'), ('CANCELED_BY_CLINIC', 'Cancelado pela clínica')], default='REQUESTED', max_length=30)),
                ('clinical_notes', models.TextField(blank=True, help_text='Notas clínicas (idealmente criptografadas; acesso só do médico).')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.clinic', verbose_name='Clínica')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_model', models.CharField(max_length=100)),
                ('target_object_id', models.CharField(help_text='ID do objeto alvo (UUID ou outro identificador)', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('READ', 'Leitura'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('EXPORT', 'Exportação')], max_length=20)),
                ('changes', models.JSONField(blank=True, help_text='Diferenças de estado (antes/depois) em updates.', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.clinic')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
    ]
