# Generated by Django 5.2.8 on 2025-11-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctor_for_secretary',
            field=models.ForeignKey(blank=True, help_text='Médico principal com quem a secretária atua.', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
