# Generated by Django 5.2.8 on 2025-11-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctorprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Usado para definir automaticamente Dr. ou Dra. para médicos.', max_length=1, null=True),
        ),
    ]
