# Generated by Django 5.2.8 on 2025-11-22 02:30

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_doctorprofile_gender_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinical_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Notas clínicas criptografadas (Fernet). Em produção, utilize chaves seguras e rotação adequada.'),
        ),
    ]
