# Generated by Django 5.2.8 on 2025-11-22 02:39

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_clinical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='cpf_hash',
            field=models.CharField(blank=True, editable=False, help_text='Hash SHA-256 do CPF normalizado (somente dígitos).', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cpf',
            field=fernet_fields.fields.EncryptedCharField(help_text='CPF criptografado (apenas app exibe em texto).', max_length=14),
        ),
    ]
