# Generated by Django 5.2.8 on 2025-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patientprofile_cpf_hash_alter_patientprofile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Notas clínicas (idealmente criptografadas; acesso só do médico).'),
        ),
    ]
