# Generated by Django 5.2.8 on 2025-11-22 15:20

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_clinical_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinical_notes',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='Notas clínicas criptografadas; acesso só do médico.'),
        ),
    ]
