# Generated by Django 5.2.8 on 2025-11-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Data de nascimento do paciente.', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não informar')], help_text='Sexo do paciente.', max_length=1, null=True),
        ),
    ]
