# Generated by Django 5.2.8 on 2025-11-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientprofile_birth_date_patientprofile_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='userconsent',
            options={'verbose_name': 'Consentimento de Usuário', 'verbose_name_plural': 'Consentimentos de Usuários'},
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cpf_hash',
            field=models.CharField(blank=True, editable=False, help_text='Hash SHA-256 do CPF normalizado (somente dígitos).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='core.legaldocument'),
        ),
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together={('user', 'document')},
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doc_type',), name='uniq_active_legal_document_per_type'),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.UniqueConstraint(fields=('clinic', 'cpf_hash'), name='uniq_patient_cpf_hash_per_clinic'),
        ),
    ]
