# Generated by Django 5.2.8 on 2025-11-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, help_text='Código numérico de 6 dígitos enviado por e-mail.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora de expiração do código de verificação.', null=True),
        ),
    ]
