# Generated by Django 5.2.8 on 2025-11-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailverificationtoken_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='code',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
